environment:
  nodejs_version: "12"
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> yarn.lock

install:
  - ps: Install-Product node $env:nodejs_version x64
  - git submodule sync
  - git submodule update --init --recursive
test_script:
  - yarn test
build: off

